# Generated by Django 4.1.7 on 2023-04-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_id',
        ),
    ]
