# Generated by Django 4.1.7 on 2023-04-14 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_remove_comment_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='women.women', verbose_name='Пост'),
        ),
    ]
