# Generated by Django 4.1.7 on 2023-04-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_comment_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
